# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rafael Sampaio
email: contact@rafaelsampaio.net
description: >- # this means to ignore newlines until "baseurl:"
  Just another tech blog with sprinkles of my personal thoughts.
url: https://rafaelsampaio.net
twitter_username: rafs_samp
github_username: rafasamp
minimal_mistakes_skin: dark
search: true
breadcrumbs: true  # disabled by default
logo: /assets/images/logo.png
comments:
  provider: "disqus"
  disqus:
    shortname: "rafaelsampaio"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-NQTEGRJ6DZ"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US/Eastern # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: en-US
repository: rafasamp/rafasamp.github.io

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rafael Sampaio"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Playing in the cloud for 14 years and loving music for over 30"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.rafaelsampaio.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rafs_samp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rafasamp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rafael-sampaio/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rafs_samp"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rafs_samp"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rafasamp"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rafael-sampaio/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rafs_samp"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      # toc: true
      # toc_label: Contents
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/